README.md
Removed mtgox (bankrupt) and added ShapeShift (great exchange)
=> Updated the bitcoin section

README.md
- Adds anon.click to the url-shorteners
- removes ending whitespaces and some lines.
=> Adding anon.click

README.md
Add link to Bitbucket's API documentation page
=> Add Bitbucket in the Source Control section

README.md
+ added the API for live collections and channel content.
+ added content category.
=> Added qKast channel content API

README.md
=> Corrected Typo.

README.md
**[Path](https://path.com/)** is Simple, Beautiful Sharing, available on **Android** and **iOS** platform.
=> Added Path APIs

README.md
The URL to jump to the Bitcoin section was broken
=> Fix bitcoin jump-to URL

README.md
I think this is a nice one worth mentioning, even if still in BETA. I've used it and is quite comprehensive.
=> Added Pearson Dictionaries API

README.md
Access to data from Withings activity trackers and body measures
=> Added Withings API

README.md
This API is open source as well.
=> Add RestCountries API

README.md
I added the pastebin API for sharing text and code quickly.
It's free to use - you are given a developer key when you sign up.
=> Pastebin.com API

README.md
Added the _Google AdWords API_ to the **Advertising** section of the list.
=> Add Google AdWords API to the Advertising section.

README.md
Added Amazon Product Advertising API into this new category.
=> Add new category: Retail

README.md
I want to add a music API in the list, which is a centralized API SDK for top 3 Chinese music provider.
=> Add a Chinese music API

README.md
Added the [Marketcloud](https://www.marketcloud.it) API under the commerce section.
=> Added Marketcloud API under the Commerce section

README.md
These APIs are commonly used by financial services companies.
=> Add identity verification APIs

README.md
Adds Videogames category and adds the first three entries
=> Adds Videogames category

README.md
Few Image moderation per API services
=> Add 3 Image moderation API services

README.md
Adding Untappd API to Social Media section
=> Adding Untappd API

README.md
=> Fix spelling of thorough

README.md
alphabetized APIs, added PubNub, Clarifai, Star Wars, RunKeeper
=> alphabetized, new APIs

README.md
Added Stripe and Braintree under Commerce.
=> Add Stripe and Braintree APIs

README.md
Added LinkedData.Center SPARQL APIs to Big Data and Analytics section.
=> SPARQL APIs

README.md
Added a link to The Guardian's excellent API.
=> Add The Guardian news API

README.md
+ API Test Center (swagger app)
=> Adding Labs64 NetLicensing RESTful API

README.md
Hi, thanks for this great list!
I added Yogurl.io an open source API and CLI tool for instant file and code serving/sharing.
Let me know if you need some changes or anything wrong 👍
=> Added Yogurl API

README.md
=> Fwix doesn't exist anymore

README.md
AerisWeather is a small weather data company that prides itself on being friendly to developers and the development community. We found your list from a post on reddit and love all the resources it aggregates. We really hope your readers enjoy our documentation and our free tier to create really cool products. Thanks!
=> Add Weather - AerisWeather

README.md
I added two APIs for getting quotes.
Since this is my first contribution on GitHub, let me know if everything is ok, or should I change anything.
Thanks.
=> Quotes APIs added

README.md
TheSportsDB has a free JSON API, more details and instructions on [the forum here](http://www.thesportsdb.com/forum/viewtopic.php?f=7&t=1799&sid=e0d2edaf455206535b85451dece00038)
API is free to use, very simple and fast. Site is crowd sourced, but also updates Soccer, Ice Hockey and Basketball, American football results automatically using importers. Also includes Rugby, Golf, Motoracing, Boxing, UFC, Wrestling and loads of others. Test api key is available to use instantly. Published production apps will need an API key which can be requested on the forums.
**A few site stats**
Total Sports Events: 73,055 
Total Sports Players: 15,806 
Total Sports Teams: 1,988
Total Artwork: 29,758
Total user edits: 49,246
**Wrappers**
Python: https://github.com/enen92/script.module.thesportsdb
PHP: …
=> Add Sports - TheSportsDB.com free JSON API

README.md
Adding GitLab to Source Control API List
=> Add GitLab

README.md
Added a currency category and a currency exchange api
=> Add Currency exchange

README.md
I added a new category - `medical` - containing two APIs
=> Add medical APIs - infermedica and lexigram

README.md
=> Added Unplugg Forecasting API

README.md
Added under Weather header. The Weatherbit API offers some unique features not seen in some of the other API offerings in this category. Thought it would be appropriate to list here!
Thanks.
=> Added the Weatherbit API.

README.md
Quick correction on typo in name of Musixmatch api.
=> Corrected typo in name of Musixmatch api.

README.md
Adding whitepages pro API used for identity verification globally.
=> Add Whitepages Pro

README.md
a open source twitter competitor with a great API : https://github.com/tootsuite/mastodon
=> add mastodon API

README.md
Face processing (detection, recognition, emotional analysis).
=> Add Skybiometry API

README.md
I hope you don't mind me creating a PR without an issue :smile:
=> Added Chuck Norris API

README.md
=> Added Verizon Cloud APIs

README.md
- Create Storage category
- Add JSONbin.io
=> Add JSONbin.io

README.md
- API is open source and available towards everyone. This gives you a comprehensive list of food reports, along with nutritional facts. It might be helpful for someone creating some sort of weight tracker app or fitness app.
=> Added USDA API - Informational Food Report and Nutritional Data.

README.md
OMDB API is now going private and subscription based. One need to be a [Patreon](https://www.patreon.com/bePatron?u=5038490) supporter of API author to get API access.
=> Updated description of OMDB API.

README.md
Text to speech is a fantastic area for development, and I have used it personally on countless occasions. VoiceRSS has an excellent free plan, with a gracious limit of 350 requests/day. There are a couple of more TTS API's, which I will have to dig through my bookmarks to find.
=> Add text to speech section

README.md
In my previous PR #170, I write it in the wrong category (89545d5c12b161608acc85757b1ef56822f67024)
=> Add Clash Royale public API

README.md
Hello,
I added [microlink.io](https://microlink.io) API. I placed it in the most relevant category.
=> Add Microlink

README.md
Aircraft and aviation continue to become a more prominent part of the technology field as the latest software and hardware systems are integrated into cutting edge flying machines. With the rise of drone technology, too, an awareness of the current 'state of the skies' is increasingly important.
This API allows software developers to follow that trend, and integrate real-time and historical flight information into their applications - whether it's for data analytics, application enhancements, or 'just for kicks.' 
ADS-B refers to the technology used by aircraft to transmit position information, registration details, and more. ADS-B receivers across the globe collect this information and populate it into a central database. You can learn more about this [aircraft tracking technology on …
=> Add "ADS-B Exchange" to the API list

README.md
Add [Africa's Talking](https://africastalking.com) which provides APIs for accessing African telco services.
=> Add Africa's Talking

README.md
Here's the URL of Quotes on Design
https://quotesondesign.com/api-v4-0/
=> Added Quotes on Design

README.md
API.AI has renamed to Dialogflow
=> Rename API.AI to DialogFlow, and update its URL

README.md
Added "Word Associations API". Section "Natural Language Processing".
=> Request to add "Word Associations API"

README.md
Use the new Spotify for Developers site and expand description to be more up-to-date
=> Update Spotify link and description

README.md
See the website for more info https://www.mailgun.com
=> Add MailGun to Communication section

README.md
Link Preview is a RESTful API that returns JSON formatted summary with title, description and preview image for any requested URL. Free & paid plans.
=> LinkPreview API

README.md
Adds Nexmo under Communication.
=> + Communication  > Nexmo

README.md
Added Oxford Dictionary service under Dictionary section.
=> Added Oxford Dictionary to Dictionary section

README.md
This will help users to use Collections and Testing Sandbox of Postman
=> Added Postman API to "Design and Discovery of APIs"

README.md
Website is down.  I think they closed
=> Remove Biteasy

README.md
New API added to the natural language processing section.
=> Added new API

README.md
Adding Ticksel to analytics category
=> Add Ticksel

README.md
Add DigitalOcean Spaces to File Storage and Manipulation
https://www.digitalocean.com/products/spaces/
=> Add DigitalOcean Spaces

README.md
Foreign exchange rates API  with currency conversion @ https://exchangeratesapi.io/
Exchange rates API is a free service for current and historical foreign exchange rates published by the European Central Bank
=> add ExchangeratesAPI.io

README.md
Add AI Mastering API to music category.
=> Add AI Mastering API

README.md
Added typeform's API (link and description) under miscellaneous
=> Added Typeform's API

README.md
Add MySocialApp API to Social Media
=> Add MySocialApp

README.md
This commit adds a known public, free-to-use API.
Also fixes some minor formatting issues.
=> Add WorldTimeAPI

README.md
Also, organizes Entertainment alphabetically.
=> Add Cat as a Service (CATAAS)

README.md
I added coinpaprika API address in Bitcoin/Bitcoin Wallets section
=> coinpaprika API

README.md
=> Add genius music api

README.md
Adding the Rocketium Video API solutions to miscellaneous section.
=> Add Rocketium Video API 

README.md
Added Random User Generator API for generation of random user information, much like Lorem Ipsum but here it's for the user.
=> Added RandomUserGenerator API 

README.md
Added reference for Poland's National Bank API in Finance section
=> Added API in finance section

README.md
Foreign currency exchange rates api with currency conversion
Rates API is a free service for current and historical foreign exchange rates built on top of data published by European Central Bank. Rates API is compatible with any application and programming languages.
=> added ratesapi.io in Currency

README.md
Please add the barcode lookup API from ean-search.org.
=> add ean-search.org API

README.md
Added the Football Prediction API to the `Sport` section.
=> Add Football Prediction API

README.md
```
https://image-charts.com/chart
?chs=700x300
&chxt=x,y
&chl=2018|2017|2015
&chd=t:60,40,20
&cht=pa
&chdl=Image|Charts|Rocks
&chf=ps0-0,lg,45,ffeb3b,0.2,f443367C,1|ps0-1,lg,45,8bc34a,0.2,0096887C,1|ps0-2,lg,45,EA469E,0.2,03A9F47C,1
&chan
```
Simple! :)
=> Added image-charts

README.md
PhantAuth was designed to simplify testing for applications using OpenID Connect authentication by making use of random generated users. Like Lorem Ipsum, but for user accounts and authentication.
=> Added PhantAuth under Miscellaneous section

README.md
Corrected spelling in ChuckNorris.io's description where Chuck was accidentally written as Chuch.
=> Corrected Spelling

README.md
=> Update link for Filestack 

README.md
HyperTrack provides APIs to track business assets on the movement
=> Adding HyperTrack to transportation

README.md
Added the Rig Veda API to the `Miscellaneous` section (since we don't have a `Books` section or a `Religion`).
=> Add the Rig Veda API

CONTRIBUTING.md
We got suggested that but after checking the contributing file we couldn't find it, so here it is for future contributions 👍
=> Adds reminder to sort alphabetically

README.md
Factual has a new getting started url
=> Update link for Factual

README.md
Added the Vedic Society API to the `Miscellaneous` section.
=> Add the Vedic Society API

README.md
API for URL shortener that shortens URLs using spaces that have zero width, making them invisible to humans.
=> Add Zero Width Shortener

README.md
API for Tiny.cc URL shortener.
=> Add Tiny.cc

README.md
API for a huge wallpaper library.
=> Add Wallhaven.cc

README.md
Adding SearchLy, an API that allows you to search similarities based on song lyrics.
=> Add SearchLy API

README.md
Currently it is badly readable.
=> Properly format the introductory note

README.md
Line number: **401**  markdown syntax error has been fixed
=>  markdown syntax error has been fixed

README.md
Adding Ola api, help your users find, book and track Ola rides with ease.
=> Add Ola api

README.md
A simple API to retrieve some quotes of Breaking Bad.
=> Add Breaking Bad Quotes

README.md
Game of Thrones Quotes : a simple API to retrieve some quotes of the famous TV Show, Game of Thrones!
=> Add Game of Thrones Quotes

README.md
Holiday Oracle uses open data and machine learning techniques in a consensus algorithm to predict holidays and business days and presents this data via an API.
https://holidayoracle.io/docs/index.html
=> Added Holiday Oracle

README.md
Arranging alphabetically per code review. 
Adding another API provider to the Finance section - Alpha Vantage, a Y Combinator backed financial data provider.
=> Adding another API provider to the Finance section

README.md
- Create a new screenshots category
- Add screenshotapi.net to the list
=> add screenshotapi.net and create screenshots category

README.md
Adding Shrtlnk.dev to URL Shorteners.
=> Add Shrtlnk.dev URL Shortening API

README.md
=> Add QuickChart to Miscellaneous 

README.md
Add APIFEX language detection API
=> Add APIFEX language detection API

README.md
My Anime List API is an open-source API providing users with a wide variety of data (ratings, episodes, synopsys, etc) for specific animes, as well as a variety of information regarding anime genres.
=> Adding My Anime List API for easy anime data access

README.md
- Added the Fun Translations API under the Entertainment section as similar APIs like Marvel and Pokedex are also there.
=> Added Fun Translations API

README.md
Add APIFEX phone number validation API
=> Add APIFEX phone number validation API

README.md
Add APIFEX website text extraction API
=> Add APIFEX website text extraction API

README.md
RAWG is a API that i have used in my personal project. Helped me a lot and i think it can help other people too.
=> Add RAWG open video game database API

README.md
Add MLScrape product web scraper API
=> Add MLScrape product web scraper API

README.md
API Link: https://placegoat.com/
Github Link: https://github.com/rosshettel/placegoat
=> Add PlaceGoat API

README.md
Apifex website text extraction - Fix alphabetic ordering
Note: Your revert went to a separate branch
=> Apifex website text extraction - Fix alphabetic ordering

README.md
This is relevant for the materials scientists, engineers, industrial data scientists, etc. A considerable amount of data is opened under CC-BY-4.0
=> Add MPDS scientific data API provider

README.md
Adding ObjectCut, an API that allows you to remove background from images automatically.
=> Added ObjectCut as background removal API

README.md
Hey @n0shake 
just a small update of the pastebin URL.
Cheers,
Peter
=> Updated the Pastebin link

README.md
=> datan -> data

README.md
Please add a `hacktoberfest-accepted` label 🙃
=> Add ExchangeRate-API.com

README.md
Saidit is a clone of reddit, which is already on this list.
=> Added Saidit.net

README.md
Would appreciate a `hacktoberfest-accepted` label on this if accepted before end of month. Cheers!
=> Add Telnyx

README.md
=> Added SpeechText.AI

README.md
Added Today in History API, provides daily historical events, births and deaths.
=> Add Today In History API

README.md
[WorkOS](https://workos.com) offers a free API to authenticate users from common enterprise identity providers like Okta, Azure, OneLogin.
=> Add WorkOS in Login and Authentication

README.md
I added swapi.tech to the list in the appropriate category/alphabetical position.
=> adds star wars api to readme.

README.md
Minor tidy up - add missing space @n0shake
=> Adding missing space

README.md
Request to submit the GamerPower API.
=> Add GamerPower API

README.md
Added the free REST API Portfolio Optimizer, which allows to optimize financial portfolios.
=> Add portfoliooptimizer.io API

README.md
This PR adds the Free QR-Code generator API
=> Add Stakdeks free QR code generator.

README.md
Unixtime https://unixtime.co.za/ - Free RESTservice to convert unixtime to datetime and vice versa.
=> Added Unixtime

README.md
**Quotable** is a free and open source quotes API that allows you to fetch quotes based on query parameters. 
Added the entry in the **README** file as per the **CONTRIBUTING** guidelines.
=> added quotable api for quotes

README.md
Add https://github.com/robertoduessmann/weather-api to the list of public APIs
=> Add free weather API

README.md
AccuWeather api is one of the best weather forecasting api arounf the world. It provides the most accurate results. Along with weather forecast data if you are building an app or website it even provides with the icon sets that can be displayed on the screen.
=> Added the AccuWeather weather api

README.md
=> Added Coingecko API

README.md
=> Add Missing 💸 to AmazonS3

README.md
PHP-Noise is a free and Open Source Noise-Background-Image-Generator.
The API is documented right under the form on the website. For more documentation, you can provide the `help` parameter to the API: https://php-noise.com/noise.php?help
=> Add PHP-Noise API to Design

README.md
I removed the open source logo
=> Add Cloudflare Trace API to Miscellaneous Category

README.md
I formatted according to the guidelines in the [contribution guidelines](https://github.com/n0shake/Public-APIs/blob/master/CONTRIBUTING.md).
=> Add Covalent API to Cryptocurrency

README.md
Code is opensource:
https://github.com/postmanlabs/httpbin
=> Add Httpbin API to Miscellaneous Category

README.md
Code is opensource, the service is hosted by Cloudflare:
source code:
https://github.com/postmanlabs/httpbin
=> Add Httpbin Cloudflare API to Miscellaneous

README.md
Added LoginRadius Docs link and description to Login Authentication section
=> Added LoginRadius Docs Link

README.md
This PR changes the format of documenting the API's into a table based format.
| API | Description | Open/Trial |
| --- | ------------ | ----------- |
| API Name | API Description |  **N/A** , 💸 or ![Open Source](https://raw.githubusercontent.com/abhishekbanthia/Public-APIs/master/opensource.png "Open Source") |
This PR also adds a Return to Table of Contents link at the end of every API section the code for that is
`[⬆ Back to Table of Contents](#table-of-contents)`
=> Better Document Available API's

README.md
=> Add Flowdash API to Miscellaneous Category

README.md
New PR linking to doc page as requested.
=> Add Hotstoks API to Finance

README.md
Hi!
Submitting another pull request for adding Vector Express, as there were merge conflicts on the last one. (https://github.com/n0shake/Public-APIs/pull/461)
=> Add Vector Express to File Storage and Manipulation

README.md
Hi there!
I added [rssapi.net](https://rssapi.net) to the "News" category!
=> Add rssapi.net

README.md
Forgot to fix it here: https://github.com/n0shake/Public-APIs/pull/476
This fixes the non-alphabetic ordering.
Thanks!
=> Adding icon.horse favicon API

README.md
Please add bruzu.com
Made required changes. ref https://github.com/n0shake/Public-APIs/pull/484#issuecomment-1053629732
=> Add Bruzu.com

README.md
Bored API is an API that generates a new task to do when bored, [homepage](https://www.boredapi.com/) and [documentation](https://www.boredapi.com/documentation).
It is open source and login-less API.
=> Added `Bored API` under `Miscellaneous` category

README.md
Adds the SingleColorImage API to the "Placeholder Images" section.
=> Add SingleColorImage API

README.md
=> Add Ayrshare to Social Media

README.md
My domain is close to his expiration date, so I changed the domain to the Github's free one.
=> Update CSGO API domain.

README.md
This framework contains tools and APIs used by the cyber security team for data gathering.
=> Add OSINT framework to more resources fix #506

README.md
Added League of Legends API to the Videogames section.
=> added League of Legends api

README.md
=> Added VeganCheck API

README.md
Updated the links to the Twitter sign-in and API documentation sites (dev -> developer)
=> Update links to Twitter developer documentation

README.md
Hello! this PR Add a new API to the list.
[Bible API ](https://bible-api.com/)
A JSON API for public domain and open bible translations.
cheers! :wave:
=> Add Bible API

README.md
=> Add Shadify API to Miscellaneous section

README.md
* This time with documentation created and updated
=> Dynamic QR Code API Added

README.md
=> Added Congress API

README.md
I have ensured all the requirements needed before making the request, please have a look at it. Would try to find and add some more in near future. Great initiative.
=> Added a new element in Quote's API section : Breaking Bad quotes.

README.md
=> Updated Owen Wilson Wow API URL

README.md
- Add Javascript PENDAX SDK in Cryptocurrency
- Also fixed alphabetical order in the cryptocurrency section.
=> Add PENDAX API

README.md
Added API Fruits open source project.
=> Added fruits api

README.md
=> Added Better Call Saul API

README.md
=> Added The Walking Dead API

README.md
=> Add Nick Cannon Baby API to Entertainment

README.md
=> Updated links for API's

README.md
=> Add Bluesky API to weather APIs

README.md
sportsapi.com is a directory for filtering and choosing sports data providers.
=> This commit adds 'Sports Data Providers' to Sport.

README.md
=> Fix typos and add missing words to `README.md`

README.md
=> Add LIVE-SCORE API

README.md
=> Added Buffy and Angel API

README.md
=> Update Studio Ghibli API URL.

README.md
The domain [satyr.io](https://satyr.io) is currently for sale and does not appear to be coming back anytime soon.
=> Remove satyr

README.md
=> Added South Park Quotes API

README.md
=> Add SearchApi to Miscellaneous

README.md
=> Add OpenF1 API

README.md
=> Add OpenQR Code Generator API

README.md
=> Added OpenHolidays API

README.md
=> Add OpenLigaDB API

README.md
=> Add DitchCarbon API

README.md
=> Add Api for currency exchange

README.md
=> Add StockX API

README.md
=> Added a Job resource

README.md
=> Add SSL-Checker API

README.md
=> Add Roanuz Cricket API

README.md
=> Add "Companies taking action" API

README.md
=> Add BrowserCat API to Misc. section

README.md
added NBA GraphQL API to sports section with open source tag.
=> Add NBA GraphQL

README.md
For more information see: https://endpoints.ai.cloud.ovh.net/
=> Add OVHcloud AI Endpoints

README.md
=> Add SignNow API

README.md
Hi, thanks for making this list, it's great and I have used it a couple times in the past.
This is a small PR just adding an API I created. I wasn't sure about the last step - linking to the documentation - as linking to the repository page will be guaranteed to always work, as well as that is where you can find instructions for self-hosting if that is what you prefer. The documentation page itself also does not link back to the repository. Please let me know if you prefer that it links to the documentation page regardless. [Here](https://www.world-wonders-api.org/v0/docs) is a link to the documentation page itself, whereas [here](https://github.com/Rolv-Apneseth/world-wonders-api) is the repo link.
=> feat: add `world-wonders-api`
