README.md

Wit AI is an NLP API that allows you to train an NLP algorithm by using something called as intents that can be extracted from text or audio. It can then extract the data you desire, in the form of entities, and send it back.
For example:
If I want to create a bot to convert currencies, my intent will be "currency". You train Wit by giving it multiple statements with your intent, like:
_"Can you convert **30** **INR** to **USD**?"_
_"How much is **10** **USD** in **GBP**"_
...
You also teach it what your entities are, (which are marked in bold), which you can assign names to, so in the first example
- 30 would be "amount",
- INR would be "from",
- USD would be "to"
Once you train it with enough data, it can understand intents, and extract the entities from sentences for you.
It provides a …

Add Wit AI to NLP API

---

README.md

In the social media section, I have added a link to and description of the VKontakte official API.
For the uninitiated, VK is a competitor to Facebook, and is the largest social media platform in the Russian Federation, Ukraine, Belarus, and Kazakhstan.
Additionally, I'm not sure what title capitalization is preferred, so I just did Chicago.

VKontakte API Added to the Social Media Section

---

README.md

Fixes a typo in the image source on the Pokéapi entry: `hhttps` -> `https`.

Fix typo on image source

---

README.md

We released a new Yelp API a few months back (v3), I've updated the link to point to that instead of the older one (v2).

Update Yelp API to link to the new Yelp API (v3)

---

README.md

[Newton](https://newton.now.sh/) is a micro-service for performing arithmetic and symbolic math operations. 
I've created a Math section, because it is not accurately described as a science API and other math APIs can be added later.

Add Math section and Newton API

---

README.md

Corrected "Google Geonomics API" to "Google Genomics API"

Corrected Google Genomics spelling

---

README.md

> All documentation for the Twitch API has been moved to the [Twitch Developer Website](https://dev.twitch.tv/docs).

Update Twitch link

---

README.md

TheAudioDB has a free JSON API, more details and instructions on [the forum here](http://www.theaudiodb.com/forum/viewtopic.php?f=6&t=8)
API is free to use, very simple and fast. Site is crowd sourced with 450,000 edits so far. Loads of audio data as well as artwork and charts including user ratings and user file hashes for identification. Test and production API key is available to use instantly.
**A few site stats**
Total Artists: 33,633
Albums: 160,298
Tracks: 2,010,170
File Hashes: 172,432
**Wrappers**
Dot.NET: https://github.com/BigGranu/TheAudioDB
JAVA: https://github.com/mozvip/theaudiodb-client

Add TheAudioDB Music API

---

README.md

I created this API myself. It is free to use but requires an API key to receive any data back. Keys are issued automatically, I just like to see how people use all this data that I have.

added Marijuana strains API to readme

---

README.md

The StackExchange API allows RESTful access to all the sites under the StackExchange domain. This includes StackOverflow, math.stackexchange, and more.
I was not sure where this item belongs in the various categories, since it is not exactly "Social Media", and there is no heading for "Q&A".

Add StackExchange API

---

README.md

Google Prediction API is deprecated, and replace by Cloud Machine Learning Engine

Update Goolge's cloud machine learning

---

README.md

This change would add the Who Hosts This API to the Miscellaneous section.

Who Hosts This API

---

README.md

I thought worth adding the HERE Maps API, since:
- there is a free plan which is not limited in time
- the free plan includes quite some features (map tiles, geocoding, places, routing, etc.)
Source: https://developer.here.com/plans (choose "For the Public")

Add HERE Maps API

---

README.md

Update links to 2 sites that were 404ing. 
For CartoDB, I added link to the generic list of API's they have.

Update links to 404 urls in Readme

---

README.md

Daum Maps API appears twice with exactly the same details.
Removing the one which is not at the right alphabetical place in the list.

Remove duplicated line Daum Maps API

---

README.md

ApiLeap has been sold and discontinued. ApiFlash is a working replacement for it.

Adding the ApiFlash Api

---

README.md

Fixed the markdown link for the **Perfect Tense API** entry (a space was missing)

Fix Perfect Tense API link

---

README.md

bng2latlong takes an OSGB36 easting and northing, the geographical coordinates commonly used by the UK's national mapping authority, Ordnance Survey, and converts it to WGS84 latitude and longitude, e.g. for use in Google maps. This is a common requirement and would seem to best fit under "Places".

Add bng2latlong API to Places

---

README.md

Remove Google's URL shorten service from the list since the support was turned down as of March 30, 2018.

Remove Google's URL shorten service from the list

---

README.md

Line number: 392
Previous URL: https://docs.pagecdn.com/api/public
Current URL: https://pagecdn.com/docs/public-api

Updated PageCDN URL

---

README.md

- [Yahoo Gemini API] on line 81 is not running (checked today: 06-01-2020)
- Yahoo Gemini API becomes [Verizon Media Native Ad Platform](https://developer.verizonmedia.com/native/guide/)
- Updated link on line 261

Open Access Button

---

README.md

Hey @n0shake 
Wunderlist has been acquired and shutdown by Microsoft.
Cheers,
Peter

Removing Wunderlist - acquired and shutdown by Microsoft

---

README.md

This PR adds the Free HTML to PDF converter API from api.stakdek.de.
The Link goes directly to the API documentation.
Also, the existing HTML to PDF API is not free, so I added the money symbol.
Feel free to review!

Add free html to pdf

---

README.md

I feel that Cryptocurrency will be a more appropriate heading than Bitcoin, as Bitcoin is a company which has its own cryptocurrency and the resources/apis are not limited to Bitcoin

Change Bitcoin to Cryptocurrency

---

README.md

Adding the GoTiny API to the URL Shorteners section. GoTiny is free to use, easy to implement and requires no authentication.

Add GoTiny to URL Shorteners

---

README.md

Add the TCGdex API, the URL is the new API website but currently redirect to the current documentation page

add TCGdex API

---

README.md

The existing link seems to be a dead link which redirects to https://bitcoin.org/en/.
This PR updates to point directly to the developer docs page.

Update Bitcoin link to point at developer docs

---

README.md

Open/Trial type was in the description box instead.
I've simply just updated the formatting to correct the misplaced subscription types.

Fixed formatting error in README.md

---

README.md

Reviewed contribution rules and added Codewars API to Miscellaneous. Added in the documentation website linked out into the README and provided context for the API listed.

Added Codewars to Miscellaneous API's

---

README.md

An API to fetch all information about players, clans, wars, leagues etc.
**API & documentation** - [link](https://developer.clashofclans.com/)

add `Clash Of Clans API` to `Videogames` category

---

README.md

add [anilist](https://anilist.co)'s api to entertainment section. Linked to the api [docs](https://anilist.gitbook.io/anilist-apiv2-docs/)

Add Anilist to Entertainment

---

README.md

Add DigiDates API to Calendar category
Fix a minor Markdown syntax error

Add DigiDates API to Calendar category and fix a minor syntax error

---

README.md

Add link to the Art Institute of Chicago API documentation in the "Miscellaneous" section.
This is a free public API that provides access to the Art Institute of Chicago's public data.

Add Art Institute of Chicago API
